version: 2
run:
  timeout: 5m
  issues-exit-code: 1
linter-options:
  no-config-yaml: true
linters:
  enable:
    - govet
    - staticcheck
    - unused
    - revive
    - misspell
    - gosec
    - prealloc
    - unconvert
    - bodyclose
    - ineffassign
    # Additional linters
    - errcheck        # Check error returns
    - errorlint       # More thorough error checking
    - noctx           # Functions should use context.Context
    - testifylint     # Better testify assertions
    # New linters
    - gocritic        # Code style and performance issues
    - nolintlint      # Validate nolint comments
    # - paralleltest    # Detect missing t.Parallel() (disabled - would require adding t.Parallel() to many tests)
    - thelper         # Detect missing t.Helper() in test helpers
    - wastedassign    # Find wasted assignments
    # - exhaustive      # Check exhaustive enum switches (disabled - requires significant refactoring)
    - perfsprint      # fmt.Sprintf performance issues
    - gochecknoinits  # Discourage init() functions
    - nestif          # Detect deeply nested conditionals
    # - maintidx        # Code complexity measurement (disabled - requires refactoring)
    # - containedctx    # Context should not be stored in structs (disabled - requires architectural changes)
    - modernize       # Suggest modern Go code simplifications
    - sloglint        # Ensure consistent slog usage
    - loggercheck     # Check logger key-value pairs
    - mnd             # Detect magic numbers
    - goconst         # Detect repeated strings that could be constants
    - dupword         # Detect duplicated words in comments
linters-settings:
  errorlint:
    error-functions:
      - fmt.Errorf
      - errors.New
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
  exhaustive:
    default-signifies-exhaustive: true
  nestif:
    min-complexity: 4
  maintidx:
    min-maint-index: 50  # Warn on complex functions

  mnd:
    # Magic number detector
    checks:
      - argument
      - case
      - condition
      - return
      - operation
      - assign
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "10"
      - "64"
      - "100"
      - "1000"
      - "1024"
      - "0755"
      - "0644"
      - "0600"
    ignored-functions:
      - "os\\.Chmod"
      - "os\\.Mkdir"
      - "os\\.MkdirAll"
      - "os\\.OpenFile"
      - "strconv\\."
      - "strings\\.SplitN"
      - "time\\."

  goconst:
    # Detect repeated strings that could be constants
    match-constant: true
    min-len: 3
    min-occurrences: 3
    ignore-tests: false
    numbers: true
    min-occurrences-const: 2

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  exclude-rules:
    # Allow unused parameters in benchmarks
    - path: bench.*\.go
      linters:
        - unused
