version: 2
run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - unused
    - revive
    - gocritic
    - misspell
    - gosec
    - prealloc
    - unconvert
    - bodyclose
    - ineffassign
issues:
  exclude-use-default: false