version: '3'

vars:
  BINARY_NAME: db-catalyst
  COVERAGE_FILE: coverage.out
  COVERAGE_HTML: coverage.html

tasks:
  default:
    desc: Run tests (default task)
    cmds:
      - task: test

  build:
    desc: Build the CLI binary
    env:
      CGO_ENABLED: '0'
    cmds:
      - go build -o {{.BINARY_NAME}} ./cmd/db-catalyst

  build-prod:
    desc: Build optimized binary for release
    env:
      CGO_ENABLED: '0'
    cmds:
      - go build -ldflags="-s -w -trimpath" -o {{.BINARY_NAME}} ./cmd/db-catalyst

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}} {{.BINARY_NAME}}-* coverage.out coverage.html bench-*.txt

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test-race:
    desc: Run tests with race detector
    env:
      CGO_ENABLED: '1'  # Required for race detector
    cmds:
      - go test -race ./...

  test-all:
    desc: Run all tests including race detection
    deps: [test, test-race]

  coverage:
    desc: Generate HTML coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  coverage-report:
    desc: Show coverage summary
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out | tail -1

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  staticcheck:
    desc: Run staticcheck (installs if needed)
    cmds:
      - which staticcheck || go install honnef.co/go/tools/cmd/staticcheck@latest
      - staticcheck ./...

  security:
    desc: Run gosec security checks (installs if needed)
    cmds:
      - which gosec || go install github.com/securego/gosec/v2/cmd/gosec@latest
      - gosec -quiet ./...

  vulncheck:
    desc: Run vulnerability check (installs if needed)
    cmds:
      - which govulncheck || go install golang.org/x/vuln/cmd/govulncheck@latest
      - govulncheck ./...

  lint-all:
    desc: Run all linters
    deps: [lint, vet, staticcheck]

  test-codegen:
    desc: Test code generation compiles correctly
    cmds:
      - go test ./test/e2e/... -v -run "TestGeneratedGoCode"
      - go test ./test/e2e/... -v -run "TestDBTXInterfaceCompatibility"

  build-examples:
    desc: Regenerate and build all examples
    cmds:
      - go run ./cmd/db-catalyst -c examples/simple/db-catalyst.toml
      - go run ./cmd/db-catalyst -c examples/advanced/db-catalyst.toml
      - go run ./cmd/db-catalyst -c examples/complex/db-catalyst.toml
      - go run ./cmd/db-catalyst -c examples/postgresql/db-catalyst.toml
      - go run ./cmd/db-catalyst -c examples/mysql/db-catalyst.toml
      - go build ./examples/...

  fuzz-tokenizer:
    desc: Fuzz test the tokenizer
    cmds:
      - go test -fuzz=FuzzScan -fuzztime=30s ./internal/schema/tokenizer/

  fuzz-schema:
    desc: Fuzz test the schema parser
    cmds:
      - go test -fuzz=FuzzParse -fuzztime=30s ./internal/schema/parser/

  fuzz-query:
    desc: Fuzz test the query parser
    cmds:
      - go test -fuzz=FuzzParse -fuzztime=30s ./internal/query/parser/

  fuzz-all:
    desc: Run all fuzz tests
    deps: [fuzz-tokenizer, fuzz-schema, fuzz-query]

  fuzz-postgres:
    desc: Fuzz test the PostgreSQL parser
    cmds:
      - go test -fuzz=^FuzzParser$ -fuzztime=30s ./internal/schema/parser/postgres/

  fuzz-mysql:
    desc: Fuzz test the MySQL parser
    cmds:
      - go test -fuzz=^FuzzParser$ -fuzztime=30s ./internal/schema/parser/mysql/

  fuzz-graphql:
    desc: Fuzz test the GraphQL parser
    cmds:
      - go test -fuzz=^FuzzParser$ -fuzztime=30s ./internal/parser/languages/graphql/

  fuzz-extended:
    desc: Run extended fuzz tests with larger corpus
    cmds:
      - go test -fuzz=FuzzScanExtended -fuzztime=60s ./internal/schema/tokenizer/
      - go test -fuzz=FuzzParser -fuzztime=60s ./internal/schema/parser/
      - go test -fuzz=FuzzParser -fuzztime=60s ./internal/query/parser/

  chaos:
    desc: Run chaos tests on all parsers
    cmds:
      - ./scripts/chaos.sh all

  chaos-tokenizer:
    desc: Run chaos tests on tokenizer
    cmds:
      - ./scripts/chaos.sh tokenizer

  chaos-schema:
    desc: Run chaos tests on schema parser
    cmds:
      - ./scripts/chaos.sh schema

  chaos-query:
    desc: Run chaos tests on query parser
    cmds:
      - ./scripts/chaos.sh query

  chaos-benchmark:
    desc: Run chaos benchmarks
    cmds:
      - ./scripts/chaos.sh benchmark

  mutation:
    desc: Run mutation testing (quick mode)
    cmds:
      - ./scripts/mutation.sh quick

  mutation-schema:
    desc: Run mutation testing on schema packages
    cmds:
      - ./scripts/mutation.sh schema

  mutation-query:
    desc: Run mutation testing on query packages
    cmds:
      - ./scripts/mutation.sh query

  mutation-core:
    desc: Run mutation testing on core packages
    cmds:
      - ./scripts/mutation.sh core

  mutation-all:
    desc: Run mutation testing on all packages
    cmds:
      - ./scripts/mutation.sh all

  bench:
    desc: Run all benchmarks
    cmds:
      - go test -bench=. -benchmem ./...

  bench-save:
    desc: Save benchmark results with date stamp
    cmds:
      - go test -bench=. -benchmem -count=5 ./... > bench-$(date +%Y%m%d).txt

  integration-pipeline:
    desc: Run pipeline integration tests
    cmds:
      - go test -v ./internal/pipeline/... -run "TestSimpleSchema|TestComplexSchema|TestCTEs|TestEdgeCases" -count=1

  quality:
    desc: Run all quality checks
    deps: [lint-all, test-race, coverage-report]
    cmds:
      - echo "All quality checks passed!"

  fmt:
    desc: Format all Go code
    cmds:
      - go fmt ./...

  install-deps:
    desc: Install development dependencies
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  ci:
    desc: Run CI pipeline
    deps: [lint-all, security, vulncheck, test-race, coverage-report]

  quick:
    desc: Quick build, test, and verify
    cmds:
      - go build ./cmd/db-catalyst
      - go test ./...
      - task: test-codegen
      - task: lint

  install:
    desc: Install binary to $GOPATH/bin
    cmds:
      - go install ./cmd/db-catalyst
