// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package complexdb

import (
	"context"
	"database/sql"
)

const queryDeleteAuthor string = `DELETE FROM authors WHERE id = ?;`

func (q *Queries) DeleteAuthor(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, queryDeleteAuthor, id)
}
