// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package advanceddb

import "github.com/electwix/db-catalyst/examples/advanced/types"

type Orders struct {
	Id          types.OrderID `json:"id"`
	UserId      types.UserID  `json:"user_id"`
	Status      types.Status  `json:"status"`
	TotalAmount types.Money   `json:"total_amount"`
	CreatedAt   int32         `json:"created_at"`
	UpdatedAt   *int32        `json:"updated_at"`
}
type Products struct {
	Id        types.ProductID `json:"id"`
	Sku       types.SKU       `json:"sku"`
	Name      string          `json:"name"`
	Price     types.Money     `json:"price"`
	CreatedAt int32           `json:"created_at"`
}
type Users struct {
	Id        types.UserID `json:"id"`
	Email     types.Email  `json:"email"`
	CreatedAt int32        `json:"created_at"`
}
