// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package advanceddb

import (
	"context"
	"database/sql"
)

const queryCreateUser string = `INSERT INTO users (email)
VALUES (?)
RETURNING *;`

func (q *Queries) CreateUser(ctx context.Context, arg1 any) (CreateUserRow, error) {
	rows, err := q.db.QueryContext(ctx, queryCreateUser, arg1)
	if err != nil {
		return CreateUserRow{}, err
	}
	defer func() { _ = rows.Close() }()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return CreateUserRow{}, err
		}
		return CreateUserRow{}, sql.ErrNoRows
	}
	item, err := scanCreateUserRow(rows)
	if err != nil {
		return item, err
	}
	if err := rows.Err(); err != nil {
		return item, err
	}
	return item, nil
}
