// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package advanceddb

import (
	"context"
	"database/sql"
)

const queryCreateProduct string = `INSERT INTO products (sku, name, price)
VALUES (?, ?, ?)
RETURNING *;`

func (q *Queries) CreateProduct(ctx context.Context, arg1 any, arg2 string, arg3 any) (CreateProductRow, error) {
	rows, err := q.db.QueryContext(ctx, queryCreateProduct, arg1, arg2, arg3)
	if err != nil {
		return CreateProductRow{}, err
	}
	defer func() { _ = rows.Close() }()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return CreateProductRow{}, err
		}
		return CreateProductRow{}, sql.ErrNoRows
	}
	item, err := scanCreateProductRow(rows)
	if err != nil {
		return item, err
	}
	if err := rows.Err(); err != nil {
		return item, err
	}
	return item, nil
}
