// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package postgresqldb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const queryCreateComment string = `INSERT INTO comments (post_id, user_id, commentbody)
VALUES ($1, $2, $3)
RETURNING *;`

func (q *Queries) CreateComment(ctx context.Context, arg1 *uuid.UUID, arg2 *uuid.UUID, arg3 pgtype.Text) (CreateCommentRow, error) {
	rows, err := q.db.QueryContext(ctx, queryCreateComment, arg1, arg2, arg3)
	if err != nil {
		return CreateCommentRow{}, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return CreateCommentRow{}, err
		}
		return CreateCommentRow{}, sql.ErrNoRows
	}
	item, err := scanCreateCommentRow(rows)
	if err != nil {
		return item, err
	}
	if err := rows.Err(); err != nil {
		return item, err
	}
	return item, nil
}
