// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package postgresqldb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const queryIncrementPostViews string = `UPDATE posts SET view_count = view_count + 1 WHERE id = $1;`

func (q *Queries) IncrementPostViews(ctx context.Context, arg1 uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, queryIncrementPostViews, arg1)
}
