// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package postgresqldb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const queryRemoveTagFromPost string = `DELETE FROM post_tags WHERE post_id = $1 AND tag_id = $2;`

func (q *Queries) RemoveTagFromPost(ctx context.Context, arg1 *uuid.UUID, arg2 *uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, queryRemoveTagFromPost, arg1, arg2)
}
