// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package postgresqldb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const queryUpdateUser string = `UPDATE users
SET username = $2, useremail = $3, metadata = $4, tags = $5, updated_at = NOW()
WHERE id = $1
RETURNING *;`

func (q *Queries) UpdateUser(ctx context.Context, arg2 pgtype.Text, arg3 pgtype.Text, arg4 *[]byte, arg5 pgtype.Text, arg1 uuid.UUID) (UpdateUserRow, error) {
	rows, err := q.db.QueryContext(ctx, queryUpdateUser, arg2, arg3, arg4, arg5, arg1)
	if err != nil {
		return UpdateUserRow{}, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return UpdateUserRow{}, err
		}
		return UpdateUserRow{}, sql.ErrNoRows
	}
	item, err := scanUpdateUserRow(rows)
	if err != nil {
		return item, err
	}
	if err := rows.Err(); err != nil {
		return item, err
	}
	return item, nil
}
