// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package postgresqldb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const queryDeleteComment string = `DELETE FROM comments WHERE id = $1;`

func (q *Queries) DeleteComment(ctx context.Context, arg1 uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, queryDeleteComment, arg1)
}
