// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package postgresqldb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const queryAddTagToPost string = `INSERT INTO post_tags (post_id, tag_id) VALUES ($1, $2);`

func (q *Queries) AddTagToPost(ctx context.Context, arg1 *uuid.UUID, arg2 *uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, queryAddTagToPost, arg1, arg2)
}
