// Code generated by db-catalyst. DO NOT EDIT.
//nolint:revive


package postgresqldb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const queryLikeComment string = `UPDATE comments SET likes = likes + 1 WHERE id = $1;

-- Tag queries`

func (q *Queries) LikeComment(ctx context.Context, arg1 uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, queryLikeComment, arg1)
}
